services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules   # prevent node_modules from being overridden
    command: npm run start:prod
    ports:
      - 3009:${PORT}
    depends_on:
      db:
        condition: service_healthy
  db:
    image: mysql:8.0
    restart: always
    secrets:
      - db-password
    volumes:
      - db-data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/db-password
    ports:
      - ${DB_PORT}:3306
    expose:
      - ${DB_PORT}
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -uroot -p$$MYSQL_ROOT_PASSWORD --silent"]
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  db-data:
secrets:
  db-password:
    file: db/password.txt

